### PR TITLE
caddy fails with `no bin`, removing the .bin fixes it

### PR DESCRIPTION
**Pull request by sjmackenzie**

### CODE REVIEW

**Comment by chessai** [comment]
also running into this, would appreciate a merge! thanks

**Comment by ldeck** [comment]
Any chance this could be merged?

**Comment by AndersonTorres** [comment]
What about a fork?

**Comment by sjmackenzie** [comment]
I'd be happy to optimistically hit the merge button on a fractalide/styx repo. Though I think we should at least give @ericsagnes an opportunity.

**Comment by sjmackenzie** [comment]
Ah right, this repo is already in an organisation. @ericsagnes could you be a dear and give me maintainer access?

**Comment by AndersonTorres** [comment]
Well, I am afraid he is not online anymore. That way, I and some guys are thinking in fork it, just to the case...

In fact, it would be even more fun if we put it under the nix-community umbrella!

I will open an informal issue about forking styx infrastructure.

**Comment by sjmackenzie** [comment]
Actually that's a great idea (viz styx -> nix-comunity umbrella). I hope all is well with @ericsagnes ... @edolstra could you be a dear and allow styx repo to be under `nixos/styx` please?

**Comment by AndersonTorres** [comment]
@sjmackenzie Not NixOS system, but Nix community itself! 

https://github.com/nix-community/

It is like AUR, but better!

**Comment by sjmackenzie** [comment]
Oh yeah, right! I ran out of patience setting that up, but that was early days. I'll take another swing at that if the need arises! I'll point my instance to nix-community/styx. I also suggest we change styx in nixpkgs and point it to the new upstream (or whatever the protocol is ... )

**Comment by AndersonTorres** [comment]
@sjmackenzie 

Just in case: We are in a new organization now!

https://github.com/static-nix/

**Comment by ericsagnes** [comment]
@sjmackenzie Thanks!
and really sorry for the delay.

**Comment by sjmackenzie** [comment]
@ericsagnes I'm very happy you're alive! Hope things are going well over in Japan mate! Now would it be an inconvenience if we took on some maintainers to help lighten the load for this repository?

**Pull request merged**
